DCA = 0x10 - 1
CHANNEL = 0x20 - 1

characters = {
    'John': CHANNEL | 1,
    'Franklin': CHANNEL | 2,
    'Jefferson': CHANNEL | 3,
    'Dickinson': CHANNEL | 4,
    'Rutledge': CHANNEL | 5,
    'Thomson': CHANNEL | 6,
    'Mcnair': CHANNEL | 7,
    'Hancock': CHANNEL | 8,
    'Hall': CHANNEL | 9,
    'Lee': CHANNEL | 10,
    'Hopkins': CHANNEL | 11,
    'Sherman': CHANNEL | 12,
    'Read': CHANNEL | 12,
    'Livingston': CHANNEL | 13,
    'Morris': CHANNEL | 13,
    'Witherspoon': CHANNEL | 14,
    'Bartlett': CHANNEL | 14,
    'Martha': CHANNEL | 15,
    'Wilson': CHANNEL | 15,
    'Abigail': CHANNEL | 16,
    'McKean': CHANNEL | 17,
    'Rodney': CHANNEL | 18,
    'Chase': CHANNEL | 18,
    'Hewes': CHANNEL | 19,
    'Courier': CHANNEL | 20,
    'Leather Apron': CHANNEL | 21,
    'Vox': DCA | 2,
    'Band': DCA | 3,
    'FX': DCA | 4,
    'Congress': DCA | 5,
    'Conservatives': DCA | 6,
    'Glee': DCA | 7,
}
