DCA = 0x10 - 1
CHANNEL = 0x20 - 1

characters = {
    'John': CHANNEL | 0,
    'Franklin': CHANNEL | 0,
    'Thomson': CHANNEL | 0,
    'Dickinson': CHANNEL | 0,
    'Hancock': CHANNEL | 0,
    'Rutledge': CHANNEL | 0,
    'Abigail': CHANNEL | 0,
    'Lee': CHANNEL | 0,
    'Jefferson': CHANNEL | 0,
    'Hopkins': CHANNEL | 0,
    'McKean': CHANNEL | 0,
    'Martha': CHANNEL | 0,
    'Mcnair': CHANNEL | 0,
    'Chase': CHANNEL | 0,
    'Hall': CHANNEL | 0,
    'Witherspoon': CHANNEL | 0,
    'Rodney': CHANNEL | 0,
    'Wilson': CHANNEL | 0,
    'Sherman': CHANNEL | 0,
    'Courier': CHANNEL | 0,
    'Conservatives': CHANNEL | 0,
    'Bartlett': CHANNEL | 0,
    'Morris': CHANNEL | 0,
    'Read': CHANNEL | 0,
    'Glee': CHANNEL | 0,
    'Hewes': CHANNEL | 0,
    'Livingston': CHANNEL | 0,
    'All': DCA | 0,
    'Vox': DCA | 2,
    'Band': DCA | 3,
    'Congress': DCA | 4,
}
