#!/bin/bash -e
[[ -x $(which play) ]] || (echo "sox must be installed" && exit 1)

if [[ $1 == "pink" ]]; then
	play -t sl -r48000 -c2 - synth -1 pinknoise .1 40  < /dev/zero

elif [[ $1 == "white" ]]; then
  play -t sl -r48000 -c2 - synth -1 whitenoise .1 40  < /dev/zero

else
	echo "Captain's Log - Stardate" $(($(date +%C) - 19 ))$(date +%y%m%d).$(($(date +%H) *10 / 24))
	play -q -c2 -n synth whitenoise band -n 100 24 band -n 300 100 gain +30 &> /dev/null  
fi
